nu = input("Please enter the first integer: ")
nm = input("Please enter the second integer: ")
nu_value = int(nu)
nm_value = int(nm)
print "The sum of", (nu_value), "and", (nm_value), "is:", (nu_value + nm_value)
print "The difference of", (nu_value), "and", (nm_value), "is:", (nu_value - nm_value)
print "The product", (nu_value), "and", (nm_value), "is:", (nu_value * nm_value)
print "The quotient", (nu_value), "and", (nm_value), "is:", (nu_value / nm_value), "with remainder:", (nm_value % nu_value)
